### ISSUE TITLE
Shortcake crashes when it burns

### ISSUE THREAD

**Issue by chowdapowa9** [TeamMetallurgy/Agriculture#7]
I got this crash log
I tried to cook a shortcake and it crashed me when it burned I think

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 8/5/13 5:16 PM
Description: Ticking tile entity

java.lang.NullPointerException
    at com.teammetallurgy.agriculture.gui.OvenRecipes.getResult(OvenRecipes.java:132)
    at com.teammetallurgy.agriculture.machines.oven.TileEntityOven.func_70316_g(TileEntityOven.java:98)
    at net.minecraft.world.World.func_72939_s(World.java:2204)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:548)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:585)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.teammetallurgy.agriculture.gui.OvenRecipes.getResult(OvenRecipes.java:132)
    at com.teammetallurgy.agriculture.machines.oven.TileEntityOven.func_70316_g(TileEntityOven.java:98)

-- Tile entity being ticked --
Details:
    Name: AgricultureOvenTileEntity // com.teammetallurgy.agriculture.machines.oven.TileEntityOven
    Block type: ID #3000 (tile.agriculture:oven // com.teammetallurgy.agriculture.machines.oven.BlockOven)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-62,64,154), Chunk: (at 2,4,10 in -4,9; contains blocks -64,0,144 to -49,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #3000 (tile.agriculture:oven // com.teammetallurgy.agriculture.machines.oven.BlockOven)
    Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2204)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:548)

-- Affected level --
Details:
    Level name: Test
    All players: 1 total; [EntityPlayerMP['oppo210'/25, l='Test', x=-60.96, y=64.00, z=156.49]]
    Chunk stats: ServerChunkCache: 539 Drop: 0
    Level seed: -5811180708947134869
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 2;7,59x1,3x3,2;1;stronghold,biome_1,village,decoration,dungeon,lake,mineshaft,lava_lake
    Level spawn location: World: (-11,4,164), Chunk: (at 5,0,4 in -1,10; contains blocks -16,0,160 to -1,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 15434 game time, 15434 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 96370 (now: false), thunder time: 34635 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:585)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 120377680 bytes (114 MB) / 446234624 bytes (425 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 1113 (62328 bytes; 0 MB) allocated, 967 (54152 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.04 FML v6.2.35.804 Minecraft Forge 9.10.0.804 5 mods loaded, 5 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.2.35.804} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.10.0.804} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Agriculture{1.0.0} [Agriculture](Agriculture -Final.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    custom_flags{dev 1} [Custom Flags](Custom Flags Dev 2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 548 (30688 bytes; 0 MB) allocated, 363 (20328 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['oppo210'/25, l='Test', x=-60.96, y=64.00, z=156.49]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by odininon** [comment]
Fixed via abc5f5fd15f8aa69510bcd61b4186cfb6aa6525a
